In [1]:
import os
import topogenesis as tg
import pyvista as pv
import trimesh as tm
import pandas as pd
import numpy as np

In [2]:
# creating neighborhood definition
stencil = tg.create_stencil("von_neumann", 1, 1)
# setting the center to zero
stencil.set_index([0,0,0], 0)
stencil.function = tg.sfunc.sum
print(stencil)

[[[0 0 0]
  [0 1 0]
  [0 0 0]]

 [[0 1 0]
  [1 0 1]
  [0 1 0]]

 [[0 0 0]
  [0 1 0]
  [0 0 0]]]


In [3]:
# loading the lattice from csv
lattice_path = os.path.relpath('../data/meshes/voxelized_envelope_highres.csv')
avail_lattice = tg.lattice_from_csv(lattice_path)

In [4]:
# current_occupation = occ_lattice > -1
current_occupation = avail_lattice

In [5]:
current_occupation.apply_stencil(stencil)

lattice([[[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 1, 1, ..., 1, 1, 1],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],

         [[0, 0, 0, ..., 0, 0, 0],
          [0, 1, 1, ..., 1, 1, 1],
          [1, 3, 4, ..., 4, 4, 3],
          ...,
          [0, 2, 2, ..., 2, 2, 2],
          [0, 1, 1, ..., 1, 1, 1],
          [0, 0, 0, ..., 0, 0, 0]],

         [[0, 0, 0, ..., 0, 0, 0],
          [0, 1, 1, ..., 1, 1, 1],
          [1, 4, 5, ..., 5, 5, 4],
          ...,
          [1, 4, 5, ..., 5, 5, 4],
          [1, 3, 4, ..., 4, 4, 3],
          [0, 1, 1, ..., 1, 1, 1]],

         ...,

         [[0, 1, 1, ..., 1, 1, 1],
          [1, 4, 5, ..., 5, 5, 4],
          [1, 5, 6, ..., 6, 6, 5],
          ...,
          [1, 5, 6, ..., 6, 6, 5],
          [1, 4, 5, ..., 5, 5, 4],
          [0, 1, 1, ..., 1, 1, 1]],

         [[0, 1, 1, ..., 1, 1, 1],
          [1, 4, 5, ..., 5, 5, 4],
       

In [6]:
current_facade = avail_lattice == 0 and current_occupation > 0

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()