Import stuff

In [1]:
import os
import topogenesis as tg
import pyvista as pv
import trimesh as tm
import numpy as np

#pv.set_jupyter_backend("ipyvtklink")

# convert mesh to pv_mesh
def tri_to_pv(tri_mesh):
    faces = np.pad(tri_mesh.faces, ((0, 0),(1,0)), 'constant', constant_values=3)
    pv_mesh = pv.PolyData(tri_mesh.vertices, faces)
    return pv_mesh

Import Envelope Lattice/streetnetwork

In [6]:
# loading the lattice from csv
lattice_path = os.path.relpath('../data/meshes/voxelized_envelope.csv')
envelope_lattice = tg.lattice_from_csv(lattice_path)
envelope_lattice.shape

env_cens = envelope_lattice.centroids_threshold(-1)

print (env_cens)

# import the streetnetwork as a point cloud (workshop file, temporary)
street_path = os.path.relpath("../data/meshes/street_points.csv")
street_pc = tg.cloud_from_csv(street_path)

print (street_pc)

[[ -40. -100.    0.]
 [ -40. -100.    5.]
 [ -40. -100.   10.]
 ...
 [ 110.  -15.   25.]
 [ 110.  -15.   30.]
 [ 110.  -15.   35.]]
[[110.843811 -15.886814   0.      ]
 [107.933852 -15.902198   0.      ]
 [105.023892 -15.917581   0.      ]
 [102.113933 -15.932964   0.      ]
 [ 99.203974 -15.948348   0.      ]
 [ 96.294014 -15.963731   0.      ]
 [ 93.384055 -15.979115   0.      ]
 [ 90.474096 -15.994498   0.      ]
 [ 87.564136 -16.009882   0.      ]
 [ 84.654177 -16.025265   0.      ]
 [ 81.744218 -16.040649   0.      ]
 [ 78.834258 -16.056032   0.      ]
 [ 75.924299 -16.071415   0.      ]
 [ 73.01434  -16.086799   0.      ]
 [ 70.10438  -16.102182   0.      ]
 [ 67.194421 -16.117566   0.      ]
 [ 64.284462 -16.132949   0.      ]
 [ 61.374502 -16.148333   0.      ]
 [ 58.464543 -16.163716   0.      ]
 [ 55.554584 -16.1791     0.      ]
 [ 52.644624 -16.194483   0.      ]
 [ 49.734665 -16.209867   0.      ]
 [ 46.824706 -16.22525    0.      ]
 [ 43.914746 -16.240633   0.      ]
 [ 4

Calculate distance

In [7]:
# extracting the centroid of all voxels
env_cens = something
#print(env_cens.size)
# initializing the distance matrix
dist_m = []
# for each voxel ...
for voxel_cen in env_cens:
    # initializing the distance vector (per each voxel)
    dist_v = []
    # for each street point ...
    for street_point in street_pc:
        # find the difference vector
        diff = voxel_cen - street_point
        # raise the components to the power of two
        diff_p2 = diff**2
        # sum the components
        diff_p2s = diff_p2.sum()
        # compute the square root 
        dist = diff_p2s**0.5
        # add the distance to the distance vector
        dist_v.append(dist)
    # add the distance vector to the distance matrix
    dist_m.append(dist_v)
# change the distance matrix type, from list to array
dist_m = np.array(dist_m)
#print(dist_m.size, dist_m.shape)

# find the distance to the closest street point for each voxel
min_dist = dist_m.min(axis=1)

np_lat = np.array(env_cens)

#np.append(np_lat, min_dist)

loudness = []

#for count in range(len(np_lat)):
#   new_array.append(np.append(np_lat[count], min_dist[count]))

for count, lat_val in enumerate(np_lat):
   loudness.append(np.append(lat_val, min_dist[count]))

loudness

[array([110.843811, -15.886814,   0.      ,   0.      ]),
 array([107.933852, -15.902198,   0.      ,   0.      ]),
 array([105.023892, -15.917581,   0.      ,   0.      ]),
 array([102.113933, -15.932964,   0.      ,   0.      ]),
 array([ 99.203974, -15.948348,   0.      ,   0.      ]),
 array([ 96.294014, -15.963731,   0.      ,   0.      ]),
 array([ 93.384055, -15.979115,   0.      ,   0.      ]),
 array([ 90.474096, -15.994498,   0.      ,   0.      ]),
 array([ 87.564136, -16.009882,   0.      ,   0.      ]),
 array([ 84.654177, -16.025265,   0.      ,   0.      ]),
 array([ 81.744218, -16.040649,   0.      ,   0.      ]),
 array([ 78.834258, -16.056032,   0.      ,   0.      ]),
 array([ 75.924299, -16.071415,   0.      ,   0.      ]),
 array([ 73.01434 , -16.086799,   0.      ,   0.      ]),
 array([ 70.10438 , -16.102182,   0.      ,   0.      ]),
 array([ 67.194421, -16.117566,   0.      ,   0.      ]),
 array([ 64.284462, -16.132949,   0.      ,   0.      ]),
 array([ 61.37