Import stuff

In [17]:
import os
import topogenesis as tg
import pyvista as pv
import trimesh as tm
import numpy as np

#pv.set_jupyter_backend("ipyvtklink")

# convert mesh to pv_mesh
def tri_to_pv(tri_mesh):
    faces = np.pad(tri_mesh.faces, ((0, 0),(1,0)), 'constant', constant_values=3)
    pv_mesh = pv.PolyData(tri_mesh.vertices, faces)
    return pv_mesh

Import Envelope Lattice

In [18]:
# loading the lattice from csv
lattice_path = os.path.relpath('../data/meshes/voxelized_envelope.csv')
envelope_lattice = tg.lattice_from_csv(lattice_path)
envelope_lattice.shape

env_cens = envelope_lattice.centroids_threshold(-1)

print (env_cens)

[[ -40. -100.    0.]
 [ -40. -100.    5.]
 [ -40. -100.   10.]
 ...
 [ 110.  -15.   25.]
 [ 110.  -15.   30.]
 [ 110.  -15.   35.]]


Calculate the border points (this calculates the border voxels of the envelope, not the points on the street)

In [19]:
border_lattice = envelope_lattice * 0.0
# border_lattice[:,:,1:-1] += 1.0
border_lattice[:,1:-1,:] += 1.0
border_lattice[1:-1,:,:] += 1.0
border_lattice = border_lattice != 2
border_lattice.centroids

cloud([[ -40., -100.,    0.],
       [ -40., -100.,    5.],
       [ -40., -100.,   10.],
       ...,
       [ 110.,  -15.,   25.],
       [ 110.,  -15.,   30.],
       [ 110.,  -15.,   35.]])

Plotting the code above

In [20]:
p = pv.Plotter(notebook=True)

base_lattice = border_lattice

# Set the grid dimensions: shape + 1 because we want to inject our values on the CELL data
grid = pv.UniformGrid()
grid.dimensions = np.array(base_lattice.shape) + 1
# The bottom left corner of the data set
grid.origin = base_lattice.minbound - base_lattice.unit * 0.5
# These are the cell sizes along each axis
grid.spacing = base_lattice.unit 

# adding the boundingbox wireframe
p.add_mesh(grid.outline(), color="grey", label="Domain")

# adding the availability lattice
envelope_lattice.fast_vis(p)

# adding axes
p.add_axes()
p.show_bounds(grid="back", location="back", color="#aaaaaa")


# Add the data values to the cell data
grid.cell_arrays["Agents"] = base_lattice.flatten(order="F").astype(int)  # Flatten the array!
# filtering the voxels
threshed = grid.threshold([0.9, 1.1])
# adding the voxels
p.add_mesh(threshed, name='sphere', show_edges=True, opacity=1.0, show_scalar_bar=False)


# p.add_slider_widget(create_mesh, [0, n_frames], title='Time', value=0, event_type="always", style="classic", pointa=(0.1, 0.1), pointb=(0.9, 0.1))
p.show(use_ipyvtk=True)

ViewInteractiveWidget(height=768, layout=Layout(height='auto', width='100%'), width=1024)

[(239.8279062084888, 147.3279062084888, 222.3279062084888),
 (35.0, -57.5, 17.5),
 (0.0, 0.0, 1.0)]

Calculating the points on the street (defect)

In [27]:
#calculating maximum and minimum values

#minimum values for x and y
xmin, ymin, zmin = env_cens.min(axis=0)

print (xmin)
print (ymin)

#maximum values for x and y
xmax, ymax, zmax = env_cens.max(axis=0)

print (xmax)
print (ymax)

#calculating the points on the street

#calculate the x coördinates
x = np.arange (xmin, xmax)

#calculate the y coördinates
y = np.arange (ymin, ymax)

X = np.tile(x,(2, 1) )
Y = np.tile(y,(2, 1) )
#print(Y.T.shape)
print(X)
Z = np.zeros((2, 2))
#print(Z.shape)
something = np.stack([X.flatten(),Y.T.flatten(),Z.flatten()]).T
street_points = tg.cloud(something)
#print (something)


-40.0
-100.0
110.0
-15.0
[[-40. -39. -38. -37. -36. -35. -34. -33. -32. -31. -30. -29. -28. -27.
  -26. -25. -24. -23. -22. -21. -20. -19. -18. -17. -16. -15. -14. -13.
  -12. -11. -10.  -9.  -8.  -7.  -6.  -5.  -4.  -3.  -2.  -1.   0.   1.
    2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.  15.
   16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.  28.  29.
   30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.  42.  43.
   44.  45.  46.  47.  48.  49.  50.  51.  52.  53.  54.  55.  56.  57.
   58.  59.  60.  61.  62.  63.  64.  65.  66.  67.  68.  69.  70.  71.
   72.  73.  74.  75.  76.  77.  78.  79.  80.  81.  82.  83.  84.  85.
   86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.  98.  99.
  100. 101. 102. 103. 104. 105. 106. 107. 108. 109.]
 [-40. -39. -38. -37. -36. -35. -34. -33. -32. -31. -30. -29. -28. -27.
  -26. -25. -24. -23. -22. -21. -20. -19. -18. -17. -16. -15. -14. -13.
  -12. -11. -10.  -9.  -8.  -7.  -6.  -5.  -4.  -3.  -2.  

ValueError: all input arrays must have the same shape

Visualizing